import 'package:flutter/widgets.dart' show Brightness;
import 'package:fluttersdk_wind/fluttersdk_wind.dart';

import 'watchools_status_tokens.dart';
import 'wind_theme.g.dart';

/// Border radii, mirroring DESIGN.md's `rounded:` block.
///
/// Hand-authored because `design:sync` emits colours only. Without this map
/// every radius falls back to Wind's own scale, which is roughly double ours at
/// the small end, and the 2px fact chip that the whole badge vocabulary rests
/// on would render at 4px and stop reading as a texture.
const Map<String, double> watchoolsBorderRadius = <String, double>{
  'none': 0,
  'sm': 2,
  'DEFAULT': 4,
  'md': 6,
  'lg': 8,
  'xl': 12,
  '2xl': 16,
  '3xl': 24,
  'full': 9999,
};

/// Font families, mirroring DESIGN.md's `typography:` block.
///
/// One family carries the whole product. The value is a single Flutter family
/// name, never a CSS stack: Flutter matches one registered family and does not
/// fall through a comma-separated list the way a browser does.
///
/// `mono` is deliberately absent so it keeps Wind's default. The EPG time
/// column uses this family with tabular figures rather than a monospace,
/// because a monospaced `20:45` sits wider than the channel name beside it and
/// breaks the row rhythm.
const Map<String, String> watchoolsFontFamilies = <String, String>{'sans': 'Schibsted Grotesk'};

/// Assembles the app's Wind theme from both halves of DESIGN.md.
///
/// The colour half (`designColors` plus `designAliases`) is generated by
/// `./bin/fsa design:sync`. The playback status families and the radius and
/// font scales are hand-authored, because `design:sync` emits none of them.
///
/// Keeping the assembly here rather than inline in `main()` gives the theme one
/// definition that the app and its tests both read, so a test cannot pass
/// against a theme the app does not ship.
/// `syncWithSystem` is off and `brightness` is pinned dark. Wind documents this
/// as divergence F05: a declarative brightness loses to the system value unless
/// sync is disabled, so `MagicApplication(themeMode: ThemeMode.dark)` alone
/// renders light on a light-mode machine. Measured, not assumed.
WindThemeData buildWatchoolsWindTheme() => WindThemeData(
  colors: designColors,
  aliases: <String, String>{...designAliases, ...watchoolsStatusAliases},
  borderRadius: watchoolsBorderRadius,
  fontFamilies: watchoolsFontFamilies,
  brightness: Brightness.dark,
  syncWithSystem: false,
);
